// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"license-manager/pkg/repositories/ent-fw/ent/claims"
	"license-manager/pkg/repositories/ent-fw/ent/credentials"
	"license-manager/pkg/repositories/ent-fw/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClaimsUpdate is the builder for updating Claims entities.
type ClaimsUpdate struct {
	config
	hooks    []Hook
	mutation *ClaimsMutation
}

// Where appends a list predicates to the ClaimsUpdate builder.
func (cu *ClaimsUpdate) Where(ps ...predicate.Claims) *ClaimsUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetKey sets the "key" field.
func (cu *ClaimsUpdate) SetKey(s string) *ClaimsUpdate {
	cu.mutation.SetKey(s)
	return cu
}

// SetValue sets the "value" field.
func (cu *ClaimsUpdate) SetValue(s string) *ClaimsUpdate {
	cu.mutation.SetValue(s)
	return cu
}

// SetClaimerID sets the "claimer" edge to the Credentials entity by ID.
func (cu *ClaimsUpdate) SetClaimerID(id int) *ClaimsUpdate {
	cu.mutation.SetClaimerID(id)
	return cu
}

// SetNillableClaimerID sets the "claimer" edge to the Credentials entity by ID if the given value is not nil.
func (cu *ClaimsUpdate) SetNillableClaimerID(id *int) *ClaimsUpdate {
	if id != nil {
		cu = cu.SetClaimerID(*id)
	}
	return cu
}

// SetClaimer sets the "claimer" edge to the Credentials entity.
func (cu *ClaimsUpdate) SetClaimer(c *Credentials) *ClaimsUpdate {
	return cu.SetClaimerID(c.ID)
}

// Mutation returns the ClaimsMutation object of the builder.
func (cu *ClaimsUpdate) Mutation() *ClaimsMutation {
	return cu.mutation
}

// ClearClaimer clears the "claimer" edge to the Credentials entity.
func (cu *ClaimsUpdate) ClearClaimer() *ClaimsUpdate {
	cu.mutation.ClearClaimer()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ClaimsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, ClaimsMutation](ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ClaimsUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ClaimsUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ClaimsUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ClaimsUpdate) check() error {
	if v, ok := cu.mutation.Key(); ok {
		if err := claims.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Claims.key": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Value(); ok {
		if err := claims.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Claims.value": %w`, err)}
		}
	}
	return nil
}

func (cu *ClaimsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   claims.Table,
			Columns: claims.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: claims.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Key(); ok {
		_spec.SetField(claims.FieldKey, field.TypeString, value)
	}
	if value, ok := cu.mutation.Value(); ok {
		_spec.SetField(claims.FieldValue, field.TypeString, value)
	}
	if cu.mutation.ClaimerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   claims.ClaimerTable,
			Columns: []string{claims.ClaimerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: credentials.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ClaimerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   claims.ClaimerTable,
			Columns: []string{claims.ClaimerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: credentials.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{claims.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ClaimsUpdateOne is the builder for updating a single Claims entity.
type ClaimsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClaimsMutation
}

// SetKey sets the "key" field.
func (cuo *ClaimsUpdateOne) SetKey(s string) *ClaimsUpdateOne {
	cuo.mutation.SetKey(s)
	return cuo
}

// SetValue sets the "value" field.
func (cuo *ClaimsUpdateOne) SetValue(s string) *ClaimsUpdateOne {
	cuo.mutation.SetValue(s)
	return cuo
}

// SetClaimerID sets the "claimer" edge to the Credentials entity by ID.
func (cuo *ClaimsUpdateOne) SetClaimerID(id int) *ClaimsUpdateOne {
	cuo.mutation.SetClaimerID(id)
	return cuo
}

// SetNillableClaimerID sets the "claimer" edge to the Credentials entity by ID if the given value is not nil.
func (cuo *ClaimsUpdateOne) SetNillableClaimerID(id *int) *ClaimsUpdateOne {
	if id != nil {
		cuo = cuo.SetClaimerID(*id)
	}
	return cuo
}

// SetClaimer sets the "claimer" edge to the Credentials entity.
func (cuo *ClaimsUpdateOne) SetClaimer(c *Credentials) *ClaimsUpdateOne {
	return cuo.SetClaimerID(c.ID)
}

// Mutation returns the ClaimsMutation object of the builder.
func (cuo *ClaimsUpdateOne) Mutation() *ClaimsMutation {
	return cuo.mutation
}

// ClearClaimer clears the "claimer" edge to the Credentials entity.
func (cuo *ClaimsUpdateOne) ClearClaimer() *ClaimsUpdateOne {
	cuo.mutation.ClearClaimer()
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ClaimsUpdateOne) Select(field string, fields ...string) *ClaimsUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Claims entity.
func (cuo *ClaimsUpdateOne) Save(ctx context.Context) (*Claims, error) {
	return withHooks[*Claims, ClaimsMutation](ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ClaimsUpdateOne) SaveX(ctx context.Context) *Claims {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ClaimsUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ClaimsUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ClaimsUpdateOne) check() error {
	if v, ok := cuo.mutation.Key(); ok {
		if err := claims.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Claims.key": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Value(); ok {
		if err := claims.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Claims.value": %w`, err)}
		}
	}
	return nil
}

func (cuo *ClaimsUpdateOne) sqlSave(ctx context.Context) (_node *Claims, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   claims.Table,
			Columns: claims.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: claims.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Claims.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, claims.FieldID)
		for _, f := range fields {
			if !claims.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != claims.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Key(); ok {
		_spec.SetField(claims.FieldKey, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Value(); ok {
		_spec.SetField(claims.FieldValue, field.TypeString, value)
	}
	if cuo.mutation.ClaimerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   claims.ClaimerTable,
			Columns: []string{claims.ClaimerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: credentials.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ClaimerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   claims.ClaimerTable,
			Columns: []string{claims.ClaimerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: credentials.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Claims{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{claims.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
