// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"license-manager/pkg/repositories/ent-fw/ent/claims"
	"license-manager/pkg/repositories/ent-fw/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClaimsDelete is the builder for deleting a Claims entity.
type ClaimsDelete struct {
	config
	hooks    []Hook
	mutation *ClaimsMutation
}

// Where appends a list predicates to the ClaimsDelete builder.
func (cd *ClaimsDelete) Where(ps ...predicate.Claims) *ClaimsDelete {
	cd.mutation.Where(ps...)
	return cd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cd *ClaimsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ClaimsMutation](ctx, cd.sqlExec, cd.mutation, cd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cd *ClaimsDelete) ExecX(ctx context.Context) int {
	n, err := cd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cd *ClaimsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: claims.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: claims.FieldID,
			},
		},
	}
	if ps := cd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cd.mutation.done = true
	return affected, err
}

// ClaimsDeleteOne is the builder for deleting a single Claims entity.
type ClaimsDeleteOne struct {
	cd *ClaimsDelete
}

// Where appends a list predicates to the ClaimsDelete builder.
func (cdo *ClaimsDeleteOne) Where(ps ...predicate.Claims) *ClaimsDeleteOne {
	cdo.cd.mutation.Where(ps...)
	return cdo
}

// Exec executes the deletion query.
func (cdo *ClaimsDeleteOne) Exec(ctx context.Context) error {
	n, err := cdo.cd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{claims.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cdo *ClaimsDeleteOne) ExecX(ctx context.Context) {
	if err := cdo.Exec(ctx); err != nil {
		panic(err)
	}
}
