// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"license-manager/pkg/repositories/ent-fw/ent/credentials"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CredentialsCreate is the builder for creating a Credentials entity.
type CredentialsCreate struct {
	config
	mutation *CredentialsMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (cc *CredentialsCreate) SetUsername(s string) *CredentialsCreate {
	cc.mutation.SetUsername(s)
	return cc
}

// SetPasswordHash sets the "password_hash" field.
func (cc *CredentialsCreate) SetPasswordHash(s string) *CredentialsCreate {
	cc.mutation.SetPasswordHash(s)
	return cc
}

// SetClaims sets the "claims" field.
func (cc *CredentialsCreate) SetClaims(m map[string]interface{}) *CredentialsCreate {
	cc.mutation.SetClaims(m)
	return cc
}

// Mutation returns the CredentialsMutation object of the builder.
func (cc *CredentialsCreate) Mutation() *CredentialsMutation {
	return cc.mutation
}

// Save creates the Credentials in the database.
func (cc *CredentialsCreate) Save(ctx context.Context) (*Credentials, error) {
	return withHooks[*Credentials, CredentialsMutation](ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CredentialsCreate) SaveX(ctx context.Context) *Credentials {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CredentialsCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CredentialsCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CredentialsCreate) check() error {
	if _, ok := cc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "Credentials.username"`)}
	}
	if v, ok := cc.mutation.Username(); ok {
		if err := credentials.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Credentials.username": %w`, err)}
		}
	}
	if _, ok := cc.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "Credentials.password_hash"`)}
	}
	if v, ok := cc.mutation.PasswordHash(); ok {
		if err := credentials.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "Credentials.password_hash": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Claims(); !ok {
		return &ValidationError{Name: "claims", err: errors.New(`ent: missing required field "Credentials.claims"`)}
	}
	return nil
}

func (cc *CredentialsCreate) sqlSave(ctx context.Context) (*Credentials, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CredentialsCreate) createSpec() (*Credentials, *sqlgraph.CreateSpec) {
	var (
		_node = &Credentials{config: cc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: credentials.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: credentials.FieldID,
			},
		}
	)
	if value, ok := cc.mutation.Username(); ok {
		_spec.SetField(credentials.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := cc.mutation.PasswordHash(); ok {
		_spec.SetField(credentials.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := cc.mutation.Claims(); ok {
		_spec.SetField(credentials.FieldClaims, field.TypeJSON, value)
		_node.Claims = value
	}
	return _node, _spec
}

// CredentialsCreateBulk is the builder for creating many Credentials entities in bulk.
type CredentialsCreateBulk struct {
	config
	builders []*CredentialsCreate
}

// Save creates the Credentials entities in the database.
func (ccb *CredentialsCreateBulk) Save(ctx context.Context) ([]*Credentials, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Credentials, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CredentialsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CredentialsCreateBulk) SaveX(ctx context.Context) []*Credentials {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CredentialsCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CredentialsCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
