// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"license-manager/pkg/repositories/ent-fw/ent/jwttoken"
	"license-manager/pkg/repositories/ent-fw/ent/predicate"
	"license-manager/pkg/repositories/ent-fw/ent/user"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JwtTokenQuery is the builder for querying JwtToken entities.
type JwtTokenQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.JwtToken
	withIssuer *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the JwtTokenQuery builder.
func (jtq *JwtTokenQuery) Where(ps ...predicate.JwtToken) *JwtTokenQuery {
	jtq.predicates = append(jtq.predicates, ps...)
	return jtq
}

// Limit the number of records to be returned by this query.
func (jtq *JwtTokenQuery) Limit(limit int) *JwtTokenQuery {
	jtq.ctx.Limit = &limit
	return jtq
}

// Offset to start from.
func (jtq *JwtTokenQuery) Offset(offset int) *JwtTokenQuery {
	jtq.ctx.Offset = &offset
	return jtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (jtq *JwtTokenQuery) Unique(unique bool) *JwtTokenQuery {
	jtq.ctx.Unique = &unique
	return jtq
}

// Order specifies how the records should be ordered.
func (jtq *JwtTokenQuery) Order(o ...OrderFunc) *JwtTokenQuery {
	jtq.order = append(jtq.order, o...)
	return jtq
}

// QueryIssuer chains the current query on the "issuer" edge.
func (jtq *JwtTokenQuery) QueryIssuer() *UserQuery {
	query := (&UserClient{config: jtq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := jtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := jtq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(jwttoken.Table, jwttoken.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, jwttoken.IssuerTable, jwttoken.IssuerColumn),
		)
		fromU = sqlgraph.SetNeighbors(jtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first JwtToken entity from the query.
// Returns a *NotFoundError when no JwtToken was found.
func (jtq *JwtTokenQuery) First(ctx context.Context) (*JwtToken, error) {
	nodes, err := jtq.Limit(1).All(setContextOp(ctx, jtq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{jwttoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (jtq *JwtTokenQuery) FirstX(ctx context.Context) *JwtToken {
	node, err := jtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first JwtToken ID from the query.
// Returns a *NotFoundError when no JwtToken ID was found.
func (jtq *JwtTokenQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jtq.Limit(1).IDs(setContextOp(ctx, jtq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{jwttoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (jtq *JwtTokenQuery) FirstIDX(ctx context.Context) int {
	id, err := jtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single JwtToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one JwtToken entity is found.
// Returns a *NotFoundError when no JwtToken entities are found.
func (jtq *JwtTokenQuery) Only(ctx context.Context) (*JwtToken, error) {
	nodes, err := jtq.Limit(2).All(setContextOp(ctx, jtq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{jwttoken.Label}
	default:
		return nil, &NotSingularError{jwttoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (jtq *JwtTokenQuery) OnlyX(ctx context.Context) *JwtToken {
	node, err := jtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only JwtToken ID in the query.
// Returns a *NotSingularError when more than one JwtToken ID is found.
// Returns a *NotFoundError when no entities are found.
func (jtq *JwtTokenQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jtq.Limit(2).IDs(setContextOp(ctx, jtq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{jwttoken.Label}
	default:
		err = &NotSingularError{jwttoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (jtq *JwtTokenQuery) OnlyIDX(ctx context.Context) int {
	id, err := jtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of JwtTokens.
func (jtq *JwtTokenQuery) All(ctx context.Context) ([]*JwtToken, error) {
	ctx = setContextOp(ctx, jtq.ctx, "All")
	if err := jtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*JwtToken, *JwtTokenQuery]()
	return withInterceptors[[]*JwtToken](ctx, jtq, qr, jtq.inters)
}

// AllX is like All, but panics if an error occurs.
func (jtq *JwtTokenQuery) AllX(ctx context.Context) []*JwtToken {
	nodes, err := jtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of JwtToken IDs.
func (jtq *JwtTokenQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, jtq.ctx, "IDs")
	if err := jtq.Select(jwttoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (jtq *JwtTokenQuery) IDsX(ctx context.Context) []int {
	ids, err := jtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (jtq *JwtTokenQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, jtq.ctx, "Count")
	if err := jtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, jtq, querierCount[*JwtTokenQuery](), jtq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (jtq *JwtTokenQuery) CountX(ctx context.Context) int {
	count, err := jtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (jtq *JwtTokenQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, jtq.ctx, "Exist")
	switch _, err := jtq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (jtq *JwtTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := jtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the JwtTokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (jtq *JwtTokenQuery) Clone() *JwtTokenQuery {
	if jtq == nil {
		return nil
	}
	return &JwtTokenQuery{
		config:     jtq.config,
		ctx:        jtq.ctx.Clone(),
		order:      append([]OrderFunc{}, jtq.order...),
		inters:     append([]Interceptor{}, jtq.inters...),
		predicates: append([]predicate.JwtToken{}, jtq.predicates...),
		withIssuer: jtq.withIssuer.Clone(),
		// clone intermediate query.
		sql:  jtq.sql.Clone(),
		path: jtq.path,
	}
}

// WithIssuer tells the query-builder to eager-load the nodes that are connected to
// the "issuer" edge. The optional arguments are used to configure the query builder of the edge.
func (jtq *JwtTokenQuery) WithIssuer(opts ...func(*UserQuery)) *JwtTokenQuery {
	query := (&UserClient{config: jtq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	jtq.withIssuer = query
	return jtq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Token string `json:"token,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.JwtToken.Query().
//		GroupBy(jwttoken.FieldToken).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (jtq *JwtTokenQuery) GroupBy(field string, fields ...string) *JwtTokenGroupBy {
	jtq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &JwtTokenGroupBy{build: jtq}
	grbuild.flds = &jtq.ctx.Fields
	grbuild.label = jwttoken.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Token string `json:"token,omitempty"`
//	}
//
//	client.JwtToken.Query().
//		Select(jwttoken.FieldToken).
//		Scan(ctx, &v)
func (jtq *JwtTokenQuery) Select(fields ...string) *JwtTokenSelect {
	jtq.ctx.Fields = append(jtq.ctx.Fields, fields...)
	sbuild := &JwtTokenSelect{JwtTokenQuery: jtq}
	sbuild.label = jwttoken.Label
	sbuild.flds, sbuild.scan = &jtq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a JwtTokenSelect configured with the given aggregations.
func (jtq *JwtTokenQuery) Aggregate(fns ...AggregateFunc) *JwtTokenSelect {
	return jtq.Select().Aggregate(fns...)
}

func (jtq *JwtTokenQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range jtq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, jtq); err != nil {
				return err
			}
		}
	}
	for _, f := range jtq.ctx.Fields {
		if !jwttoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if jtq.path != nil {
		prev, err := jtq.path(ctx)
		if err != nil {
			return err
		}
		jtq.sql = prev
	}
	return nil
}

func (jtq *JwtTokenQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*JwtToken, error) {
	var (
		nodes       = []*JwtToken{}
		withFKs     = jtq.withFKs
		_spec       = jtq.querySpec()
		loadedTypes = [1]bool{
			jtq.withIssuer != nil,
		}
	)
	if jtq.withIssuer != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, jwttoken.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*JwtToken).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &JwtToken{config: jtq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, jtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := jtq.withIssuer; query != nil {
		if err := jtq.loadIssuer(ctx, query, nodes, nil,
			func(n *JwtToken, e *User) { n.Edges.Issuer = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (jtq *JwtTokenQuery) loadIssuer(ctx context.Context, query *UserQuery, nodes []*JwtToken, init func(*JwtToken), assign func(*JwtToken, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*JwtToken)
	for i := range nodes {
		if nodes[i].user_issued == nil {
			continue
		}
		fk := *nodes[i].user_issued
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_issued" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (jtq *JwtTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := jtq.querySpec()
	_spec.Node.Columns = jtq.ctx.Fields
	if len(jtq.ctx.Fields) > 0 {
		_spec.Unique = jtq.ctx.Unique != nil && *jtq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, jtq.driver, _spec)
}

func (jtq *JwtTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   jwttoken.Table,
			Columns: jwttoken.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: jwttoken.FieldID,
			},
		},
		From:   jtq.sql,
		Unique: true,
	}
	if unique := jtq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := jtq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jwttoken.FieldID)
		for i := range fields {
			if fields[i] != jwttoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := jtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := jtq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := jtq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := jtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (jtq *JwtTokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(jtq.driver.Dialect())
	t1 := builder.Table(jwttoken.Table)
	columns := jtq.ctx.Fields
	if len(columns) == 0 {
		columns = jwttoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if jtq.sql != nil {
		selector = jtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if jtq.ctx.Unique != nil && *jtq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range jtq.predicates {
		p(selector)
	}
	for _, p := range jtq.order {
		p(selector)
	}
	if offset := jtq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := jtq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// JwtTokenGroupBy is the group-by builder for JwtToken entities.
type JwtTokenGroupBy struct {
	selector
	build *JwtTokenQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (jtgb *JwtTokenGroupBy) Aggregate(fns ...AggregateFunc) *JwtTokenGroupBy {
	jtgb.fns = append(jtgb.fns, fns...)
	return jtgb
}

// Scan applies the selector query and scans the result into the given value.
func (jtgb *JwtTokenGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jtgb.build.ctx, "GroupBy")
	if err := jtgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JwtTokenQuery, *JwtTokenGroupBy](ctx, jtgb.build, jtgb, jtgb.build.inters, v)
}

func (jtgb *JwtTokenGroupBy) sqlScan(ctx context.Context, root *JwtTokenQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(jtgb.fns))
	for _, fn := range jtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*jtgb.flds)+len(jtgb.fns))
		for _, f := range *jtgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*jtgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jtgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// JwtTokenSelect is the builder for selecting fields of JwtToken entities.
type JwtTokenSelect struct {
	*JwtTokenQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (jts *JwtTokenSelect) Aggregate(fns ...AggregateFunc) *JwtTokenSelect {
	jts.fns = append(jts.fns, fns...)
	return jts
}

// Scan applies the selector query and scans the result into the given value.
func (jts *JwtTokenSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jts.ctx, "Select")
	if err := jts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JwtTokenQuery, *JwtTokenSelect](ctx, jts.JwtTokenQuery, jts, jts.inters, v)
}

func (jts *JwtTokenSelect) sqlScan(ctx context.Context, root *JwtTokenQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(jts.fns))
	for _, fn := range jts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*jts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
