// Code generated by ent, DO NOT EDIT.

package claims

const (
	// Label holds the string label denoting the claims type in the database.
	Label = "claims"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldValues holds the string denoting the values field in the database.
	FieldValues = "values"
	// Table holds the table name of the claims in the database.
	Table = "claims"
)

// Columns holds all SQL columns for claims fields.
var Columns = []string{
	FieldID,
	FieldValues,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "claims"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"credentials_claims",
	"jwt_token_claims",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// ValuesValidator is a validator for the "values" field. It is called by the builders before save.
	ValuesValidator func(string) error
)
