// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// Credentials is the predicate function for credentials builders.
type Credentials func(*sql.Selector)

// JwtToken is the predicate function for jwttoken builders.
type JwtToken func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)
